modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
# The modid of the mod
modId="templatemod" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Template Mod" #mandatory
logoFile="logo.png"
credits="Credits!" #optional
# A text field displayed in the mod UI
authors="petrakat" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Template for my mods
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.templatemod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[40,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.templatemod]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.templatemod]]
    modId="paucal"
    mandatory=true
    versionRange="[0.3.4,0.4.0)"
    ordering="NONE"
    side="BOTH"
